import { Timestamp } from 'firebase/firestore';

/**
 * Firestore document structure for /media/{mediaId}.
 *
 * Designed for migration safety:
 * - `storagePath` is the bucket-relative path (works on GCS, S3, R2)
 * - `downloadUrl` is CDN-ready but re-generatable from storagePath via Admin SDK
 * - Variants generated by Cloud Function post-upload; status tracks processing state
 */
export interface MediaDocument {
    /** Firestore auto-generated ID — populated after creation */
    id?: string;

    /** Bucket-relative path, e.g. 'temples/abc/hero/1234-uuid-name.webp' */
    storagePath: string;

    /** HTTPS CDN download URL. Cache immutably in Firestore, never re-call getDownloadURL at render. */
    downloadUrl: string;

    /** Generated variants from Cloud Function. Empty object until processing completes. */
    variants: {
        thumb?: string;    // 200px WebP CDN URL
        medium?: string;   // 800px WebP CDN URL
    };

    /** Firebase Auth UID of the uploader */
    uploadedBy: string;

    /** Resource type for Firestore queries and Security Rules context */
    type: 'user-avatar' | 'post-image' | 'temple-hero' | 'temple-gallery' | 'temple-doc' | 'admin';

    /** Original MIME type of the uploaded file */
    contentType: string;

    /** Byte size AFTER compression (for billing dashboards) */
    sizeBytes: number;

    /** Firestore server timestamp — used for rate limiting queries */
    createdAt: Timestamp;

    /** Cloud Function sets this. Never mark 'ready' from the client. */
    status: 'processing' | 'ready' | 'failed' | 'deleted';
}
